version: '2'
services:
  jms-nginx:
    image: nginx:1.13-alpine
    container_name: jms-nginx
    restart: always
    volumes: 
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./data/jumpserver/static:/app/jumpserver/static
    - ./data/luna:/app/luna
    ports:
    - 8080:80
  jms-jumpserver:
    build:
      context: jms   
    image: jumpserver:0.5.0
    container_name: jms-jumpserver
    hostname: jms-jumpserver
    restart: always
    tty: true
    environment:
    - DEBUG=False
    - LOG_LEVEL=INFO
    - DB_ENGINE=mysql
    - DB_HOST=mysql
    - DB_NAME=jumpserver
    - DB_USER=jms
    - DB_PASSWORD=password
    - REDIS_HOST=jms-redis
    volumes:
    - ./data/jumpserver:/app/jumpserver/data
    depends_on:
    - jms-redis
  jms-coco:
    build:
      context: coco
    image: jms-coco:0.5.0
    container_name: jms-coco
    restart: always
    environment:
    - CORE_HOST=http://jms-jumpserver:8080
    volumes: 
    - ./data/coco:/app/coco/keys
    ports:
    - 2222:2222
  jms-luna:
    build:
      context: luna
    image: jms-luna:0.5.0
    container_name: jms-luna
    tty: true
    volumes: 
    - ./data/luna:/app/luna
  jms-redis:
    image: redis:4-alpine
    command: redis-server --appendonly yes
    container_name: jms-redis
    restart: always
    volumes: 
    - ./data/redis:/data
networks:
  default:
    external:
      name: core